In [1]:
from sqlalchemy import create_engine
import pandas as pd

db_url = "postgresql://ds701_update_read:tools4dsTeamATeamB@centerbeam.proxy.rlwy.net:34068/railway"

engine = create_engine(db_url)

In [2]:
# Get all table names
table_names = pd.read_sql("""
    SELECT tablename 
    FROM pg_catalog.pg_tables 
    WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema'
""", engine)

display(table_names)


# Preview head of each table
for table in table_names['tablename']:
    print(f"\n{'='*40}")
    print(f"TABLE: {table}")
    print('='*40)
    df = pd.read_sql(f"SELECT * FROM {table} LIMIT 5", engine)
    display(df)

                    tablename
0  business_suing_individuals

========================================
TABLE: business_suing_individuals
========================================

,case_id,case_number,plaintiff_name,defendant_name,plaintiff_id,defendant_id,court_name,file_date,case_status,status_date
0,1430681,1062SP000743,"Fia Card Services, N.A.","Tarwa, Sy",13166,1430680,Worcester,20100624,Pending,20100624
1,1430746,1116SC000734,"Capital One Bank (Usa), N.A.","Qureshi, Fiaza M",5502,1430745,Fitchburg,20111109,Disposed (Statistical Purposes),20120125
2,1430780,10H77SP002906,"Citibank, N.A.","Speropolous, Daniel D",16546,1430778,Northeast,20100907,Closed,20100921
3,1430780,10H77SP002906,"Citibank, N.A.","Speropolous, Lisa M",16546,1430779,Northeast,20100907,Closed,20100921
4,1430808,1260SC001475,"Capital One Bank USA, N.A.","Perkins, Andrew",19656,1360385,Wareham,20121210,Disposed (Statistical Purposes),20130307